# Generated by Django 4.2.5 on 2023-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="profile",
            field=models.ImageField(null=True, upload_to="profiles_seller/"),
        ),
    ]
